Synopsis
AndreasMadsen/course-02456-sparsemax pull request #5
Opened 2016-10-24 13:31 UTC by FrederikWR

Tjek lige at jeres studienummer passer / tilføj ting :rabbit:

2016-10-24 13:41 UTC, AndreasMadsen requested changes
Awesome. One one comment about a lonely word.

2016-10-24 13:41 UTC, AndreasMadsen commented on latex/synopsis/project_synopsis.tex
> +motivation. This could be useful in many cases but this report will focus on the application for RNNs where sparse attention could be particularly useful (for instance when encoding-decoding long sen
`\subsection*{Motivation}` ?

2016-10-27 12:49 UTC, MarcoDalFarra commented
:ok_hand: herfra

2016-10-31 12:10 UTC, AndreasMadsen approved these changes

2016-10-31 12:11 UTC, merged